### PR TITLE
fix: `ownedBy` typo

### PR DESCRIPTION
**Pull request by therealharpaljadeja**

### CODE REVIEW

**Comment by andyrobert3** [comment]
fixing this

**Review by andyrobert3 — CHANGES_REQUESTED** [review]
You need to change the `schema.graphql` too here and run `yarn codegen`
If not, the generated schema for Profile is different

**Comment by andyrobert3** [comment]
@Nazeeh21 for visibility

**Comment by naz3eh** [comment]
Thanks, @therealharpaljadeja for the PR and @andyrobert3 for reminding me of this. Changes LGTM ! Merging!

**Comment by andyrobert3** [comment]
@Nazeeh21 should we run `yarn codegen` here to prevent ts errors?

**Comment by naz3eh** [comment]
Hey @andyrobert3, am sorry I missed your comments above. Yes we need to update the schema as well and run the above specified command to get rid of the ts errors

**Pull request merged**
