### PR TITLE
Feat/index profile

### PR DESCRIPTION
**Pull request by Amtaf**
Update on schema "comment entity"

### CODE REVIEW

**Comment by Amtaf** [comment]
@Nazeeh21

**Comment by naz3eh** [comment]
Hey, @Amtaf, sorry for the delay in the review of the pr.
I was a bit busy lately and in a conf rn, so couldn't review the pr. I have gone through the pr and have few thoughts on it, which I'll add in the review soon.

**Comment by Amtaf** [comment]
No worries, Once you are ready Just highlight the changes @Nazeeh21

**Review by naz3eh — APPROVED** [review]
I was confused because you've targeted the PR to the `main` branch. Now I've changed it base and it is showing only 1 file has been. So, it LGTM now. Thanks for the PR @Amtaf. Merging

**Comment by naz3eh** [comment]
@Amtaf if you want, you can take on other issues as well. Just comment there and I'll assign you.

**Pull request merged**
